# Generated by Django 2.1.5 on 2019-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0002_auto_20190204_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='access_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
