# Generated by Django 2.1.5 on 2019-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0005_auto_20190205_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('NFO', 'NFO'), ('CDS', 'CDS'), ('BSE', 'BSE'), ('MCX', 'MCX')], max_length=60),
        ),
    ]
