# Generated by Django 2.1.5 on 2019-02-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
    ]
