# Generated by Django 2.1.5 on 2019-02-05 15:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0003_auto_20190204_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=60)),
                ('instrument_token', models.IntegerField()),
                ('exchange_token', models.IntegerField(max_length=60)),
                ('trading_symbol', models.CharField(max_length=60)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('lot_size', models.IntegerField(max_length=60)),
                ('instrument_type', models.CharField(max_length=60)),
                ('segment', models.CharField(max_length=60)),
                ('exchange', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
