# Generated by Django 2.1.5 on 2019-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0004_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='exchange_token',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lot_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
