# Generated by Django 2.1.5 on 2019-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0007_quotesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='pin',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
