# Generated by Django 2.1.5 on 2019-02-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0008_credential_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
