# Generated by Django 2.1.5 on 2019-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freaks', '0010_tempvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvalues',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
